opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_xctest_method
  - identical_operands
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - operator_usage_whitespace
  - override_in_extension
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - duplicate_imports
  - yoda_condition
  - xct_specific_matcher
  - file_header

disabled_rules:
  - line_length
  - file_length
  - type_name
  - function_body_length
  - function_parameter_count
  - identifier_name
  - cyclomatic_complexity
  - nesting
  - multiline_arguments

trailing_whitespace:
 ignores_empty_lines: true
 ignores_comments: true

file_header:
 forbidden_pattern: Created

excluded:
  - .swift-packages
  - fastlane
  - vendor

allow_zero_lintable_files: true

child_config: BundIDTests/.swiftlint_tests.yml