name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: false
      bumpBuildNumber:
        description: 'Bump build number'
        type: boolean
        required: true
        default: true

jobs:
  dependencies:
    runs-on: [self-hosted, ARM64]
    steps:
      - name: Ensure on release branch
        run: |
          echo "Ensuring current branch $GITHUB_REF is 'release' branch…"
          [[ "$GITHUB_REF" == "refs/heads/release" ]]
      - name: Setup shell
        run: |
          eval "$(rbenv init -)"
          eval "$(/opt/homebrew/bin/brew shellenv)"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Restore dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        env:
          cache-name: cache-dependencies
        with:
          path: |
            vendor
            .bundle
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Gemfile.lock', 'Brewfile') }}        
      - name: Install bundle dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: bundle install
      - name: Install brew dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: ./native_arch.sh brew bundle --no-lock
      - name: Save dependencies
        uses: actions/cache@v3
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        env:
          cache-name: cache-dependencies
        with:
          path: |
            vendor
            .bundle
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Gemfile.lock', 'Brewfile') }}

  buildForTesting:
    runs-on: [self-hosted, ARM64]
    needs: dependencies
    steps:
      - name: Setup shell
        run: |
          eval "$(rbenv init -)"
          eval "$(/opt/homebrew/bin/brew shellenv)"
      - name: Check out repository code
        uses: actions/checkout@v3          
      - name: Restore dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-dependencies
        with:
          path: |
            vendor
            .bundle
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Gemfile.lock', 'Brewfile') }}       
          fail-on-cache-miss: true
      - name: Build
        run: |
            export LANG=en_US.UTF-8;
            export LANGUAGE=en_US:en;
            bundle exec fastlane build_for_testing
      - name: Save DerivedData and SwiftPM folder
        uses: actions/cache@v3
        env:
          cache-name: cache-derived-data
        with:
          path: |
            DerivedData
            .swift-packages
            fastlane/test_output
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}

  runUnitTests:
    runs-on: [self-hosted, ARM64]
    needs: buildForTesting
    steps:
      - name: Setup shell
        run: |
          eval "$(rbenv init -)"
          eval "$(/opt/homebrew/bin/brew shellenv)"
      - name: Check out repository code
        uses: actions/checkout@v3       
      - name: Restore dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-dependencies
        with:
          path: |
            vendor
            .bundle
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Gemfile.lock', 'Brewfile') }}
          fail-on-cache-miss: true
      - name: Restore build data
        uses: actions/cache@v3
        env:
          cache-name: cache-derived-data
        with:
          path: |
            DerivedData
            .swift-packages
            fastlane/test_output
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Run all tests
        run: |
            export LANG=en_US.UTF-8;
            export LANGUAGE=en_US:en;
            bundle exec fastlane test_without_building testplan:UnitTests device:"iPhone 14"
      - name: Archive xcresult
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: xcresult-${{ github.sha }}
          path: fastlane/test_output/BundesIdent.xcresult.zip

  bumpVersion:
    runs-on: [self-hosted, ARM64]
    needs: runUnitTests
    outputs:
      gitTag: ${{ steps.gitTag.outputs.gitTag }}
    steps:
      - name: Setup shell
        run: |
          eval "$(rbenv init -)"
          eval "$(/opt/homebrew/bin/brew shellenv)"
      - name: Check out repository code
        uses: actions/checkout@v3        
      - name: Restore dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        env:
          cache-name: cache-dependencies
        with:
          path: |
            vendor
            .bundle
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Gemfile.lock', 'Brewfile') }}
      - name: fastlane bump version and create tag
        env:
          VERSION: ${{ inputs.version }}
          BUMP_BUILD_NUMBER: ${{ inputs.bumpBuildNumber }}
          GITHUB_ENV: ${{ env.GITHUB_ENV }}
        run: |
            export LANG=en_US.UTF-8;
            export LANGUAGE=en_US:en;
            bundle exec fastlane bumpVersion
      - name: Export git tag
        id: gitTag
        env:
          VERSION: ${{ env.GIT_TAG }}
        run: echo "::set-output name=gitTag::${{ env.GIT_TAG }}"
          
  production:
    runs-on: [self-hosted, ARM64]
    needs: bumpVersion
    steps:
      - name: Setup shell
        run: |
          eval "$(rbenv init -)"
          eval "$(/opt/homebrew/bin/brew shellenv)"
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.bumpVersion.outputs.gitTag }}
      - name: Restore dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        env:
          cache-name: cache-dependencies
        with:
          path: |
            vendor
            .bundle
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Gemfile.lock', 'Brewfile') }}  
      - name: Install the Apple certificate and provisioning profile
        env:
          DISTRIBUTION_CERTIFICATE_P12_BASE64: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12_BASE64 }}
          DISTRIBUTION_CERTIFICATE_P12_PASSWORD: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12_PASSWORD }}
          DISTRIBUTION_PROVISIONING_PROFILE_BASE64: ${{ secrets.PRODUCTION_DISTRIBUTION_PROVISIONING_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APPSTORECONNECT_API_KEY_JSON: ${{ secrets.APPSTORECONNECT_API_KEY_JSON }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          APPSTORECONNECT_API_KEY_PATH=$RUNNER_TEMP/api_key.json

          # import certificate and provisioning profile from secrets
          echo -n "$DISTRIBUTION_CERTIFICATE_P12_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$DISTRIBUTION_PROVISIONING_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import fastlane/AppleWWDRCAG3.cer -A -t cert -k $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH -P "$DISTRIBUTION_CERTIFICATE_P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

          echo -n "$APPSTORECONNECT_API_KEY_JSON" > $APPSTORECONNECT_API_KEY_PATH

          echo "KEYCHAIN_PATH=$KEYCHAIN_PATH" >> $GITHUB_ENV
          echo "PP_PATH=$PP_PATH" >> $GITHUB_ENV
          echo "APPSTORECONNECT_API_KEY_PATH=$APPSTORECONNECT_API_KEY_PATH" >> $GITHUB_ENV
      - name: fastlane release testflight
        env:
          APPSTORECONNECT_API_KEY_PATH: ${{ env.APPSTORECONNECT_API_KEY_PATH }}
          KEYCHAIN_PATH: ${{ env.KEYCHAIN_PATH }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          PP_PATH: ${{ env.PP_PATH }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
            export LANG=en_US.UTF-8;
            export LANGUAGE=en_US:en;
            bundle exec fastlane production
      - name: Upload xcarchive
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: BundesIdent.xcarchive.zip
          path: artifacts/*.xcarchive.zip
          if-no-files-found: error
      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision

  preview:
    runs-on: [self-hosted, ARM64]
    needs: bumpVersion
    steps:
      - name: Setup shell
        run: |
          eval "$(rbenv init -)"
          eval "$(/opt/homebrew/bin/brew shellenv)"
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.bumpVersion.outputs.gitTag }}     
      - name: Restore dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        env:
          cache-name: cache-dependencies
        with:
          path: |
            vendor
            .bundle
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Gemfile.lock', 'Brewfile') }}  
      - name: Install the Apple certificate and provisioning profile
        env:
          DISTRIBUTION_CERTIFICATE_P12_BASE64: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12_BASE64 }}
          DISTRIBUTION_CERTIFICATE_P12_PASSWORD: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12_PASSWORD }}
          PREVIEW_DISTRIBUTION_PROVISIONING_PROFILE_BASE64: ${{ secrets.PREVIEW_DISTRIBUTION_PROVISIONING_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APPSTORECONNECT_API_KEY_JSON: ${{ secrets.APPSTORECONNECT_API_KEY_JSON }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          APPSTORECONNECT_API_KEY_PATH=$RUNNER_TEMP/api_key.json

          # import certificate and provisioning profile from secrets
          echo -n "$DISTRIBUTION_CERTIFICATE_P12_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$PREVIEW_DISTRIBUTION_PROVISIONING_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import fastlane/AppleWWDRCAG3.cer -A -t cert -k $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH -P "$DISTRIBUTION_CERTIFICATE_P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

          echo -n "$APPSTORECONNECT_API_KEY_JSON" > $APPSTORECONNECT_API_KEY_PATH

          echo "KEYCHAIN_PATH=$KEYCHAIN_PATH" >> $GITHUB_ENV
          echo "PP_PATH=$PP_PATH" >> $GITHUB_ENV
          echo "APPSTORECONNECT_API_KEY_PATH=$APPSTORECONNECT_API_KEY_PATH" >> $GITHUB_ENV
      - name: fastlane preview testflight
        env:
          APPSTORECONNECT_API_KEY_PATH: ${{ env.APPSTORECONNECT_API_KEY_PATH }}
          KEYCHAIN_PATH: ${{ env.KEYCHAIN_PATH }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          PP_PATH: ${{ env.PP_PATH }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
            export LANG=en_US.UTF-8;
            export LANGUAGE=en_US:en;
            bundle exec fastlane preview
      - name: Upload xcarchive
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: BundesIdent-Preview.xcarchive.zip
          path: artifacts/*.xcarchive.zip
          if-no-files-found: error
      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
